Automating Flint Reporting Tool Environment Setup
moja-global/FLINT.Reporting pull request #19
Opened 2021-12-27 07:29 UTC by Simpleshell3

Signed-off-by: Simple Shell <simpleshell3@gmail.com>

# Automating Flint Reporting Tool Environment Setup

## Description
2
A superscript to automate the Environment Setup of the Flint Reporting Tool. Task was completed with fellow mentee @asmijafar20 under the supervision of Mentors: @Tonnix and @HarshCasper 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

$ cd ~/system/scripts/setup/environment
$ bash superscript/superscript.sh

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2021-12-27 07:31 UTC, Simpleshell3 commented
Hello,  Please review the PR
 @Tonnix , @HarshCasper and @asmijafar20 .

2021-12-27 08:13 UTC, HarshCasper requested changes

2021-12-27 08:13 UTC, HarshCasper commented on code/scripts/setup/environment/superscript/superscript.sh
> +#!bin/bash
Ensure the shebang uses an absolute path to the interpreter.

2021-12-27 08:13 UTC, HarshCasper commented on code/scripts/setup/environment/superscript/superscript.sh
> +green=`tput setaf 2`
Use $(...) notation instead of legacy backticks `...`. Please do that across the whole script.

2021-12-27 08:13 UTC, HarshCasper commented on code/scripts/setup/environment/superscript/superscript.sh
> +yellow=`tput setaf 3`
Is it being used across anywhere in the script?

2021-12-27 08:13 UTC, HarshCasper commented on code/scripts/setup/environment/superscript/superscript.sh
> +mangenta=`tput setaf 5`
Is it being used?

2021-12-27 08:13 UTC, HarshCasper commented on code/scripts/setup/environment/superscript/superscript.sh
> +black=`tput setaf 0`
Is it being used?

2021-12-27 08:13 UTC, HarshCasper commented on code/scripts/setup/environment/superscript/superscript.sh
> +read useraccount
read without -r will mangle backslashes.

2021-12-27 08:13 UTC, HarshCasper commented on code/scripts/setup/environment/superscript/superscript.sh
> +sudo adduser $useraccount
Use Double quote to prevent globbing and word splitting.

2021-12-28 13:43 UTC, HarshCasper requested changes
Can you please add some docs to use the super-script?

2021-12-28 13:47 UTC, HarshCasper approved these changes

2021-12-28 14:08 UTC, merged